export type TyreTemps = {
  left_c?: number;
  center_c?: number;
  right_c?: number;
  carcass_c?: number;
};

export type TyreState = {
  compound_front?: string;
  compound_rear?: string;
  wear_fl?: number;
  wear_fr?: number;
  wear_rl?: number;
  wear_rr?: number;
  pressure_fl?: number;
  pressure_fr?: number;
  pressure_rl?: number;
  pressure_rr?: number;
  load_fl?: number;
  load_fr?: number;
  load_rl?: number;
  load_rr?: number;
  temp_fl?: TyreTemps;
  temp_fr?: TyreTemps;
  temp_rl?: TyreTemps;
  temp_rr?: TyreTemps;
  average_wear?: number;
  average_temp_c?: number;
};

export type HybridState = {
  battery_percent?: number;
  virtual_energy_fraction?: number;
  regen_kw?: number;
  motor_state?: string;
  deploy_mode?: string;
  regen_active?: boolean;
};

export type PlayerState = {
  vehicle_name?: string;
  vehicle_model?: string;
  vehicle_class?: string;
  position?: number;
  class_position?: number;
  lap_number?: number;
  current_sector?: number;
  current_lap_time?: number;
  last_lap_time?: number;
  best_lap_time?: number;
  delta_best?: number;
  speed_kph?: number;
  gear?: number;
  rpm?: number;
  max_rpm?: number;
  engine_torque?: number;
  engine_oil_temp?: number;
  engine_water_temp?: number;
  fuel_liters?: number;
  fuel_capacity_liters?: number;
  throttle?: number;
  brake?: number;
  steering?: number;
  clutch?: number;
  speed_limiter?: boolean;
  abs_active?: boolean;
  tc_active?: boolean;
  abs_setting?: number;
  abs_max?: number;
  tc_setting?: number;
  tc_max?: number;
  tc_slip_setting?: number;
  tc_cut_setting?: number;
  brake_temp_fl?: number;
  brake_temp_fr?: number;
  brake_temp_rl?: number;
  brake_temp_rr?: number;
  brake_pressure_fl?: number;
  brake_pressure_fr?: number;
  brake_pressure_rl?: number;
  brake_pressure_rr?: number;
  ride_height_fl?: number;
  ride_height_fr?: number;
  ride_height_rl?: number;
  ride_height_rr?: number;
  suspension_deflection_fl?: number;
  suspension_deflection_fr?: number;
  suspension_deflection_rl?: number;
  suspension_deflection_rr?: number;
  front_third_deflection?: number;
  rear_third_deflection?: number;
  front_ride_height?: number;
  rear_ride_height?: number;
  front_downforce?: number;
  rear_downforce?: number;
  drag?: number;
  finish_status?: string;
  track_limits_steps?: number;
  lap_invalidated?: boolean;
  gap_car_ahead?: number;
  gap_car_behind?: number;
  gap_place_ahead?: number;
  gap_place_behind?: number;
  tyre_state?: TyreState;
  hybrid_state?: HybridState;
};

export type SessionState = {
  track_name?: string;
  session_type?: string;
  game_phase?: string;
  current_time?: number;
  end_time?: number;
  time_remaining?: number;
  max_laps?: number;
  num_vehicles?: number;
  yellow_flag_state?: string;
  current_lap?: number;
};

export type EnvironmentState = {
  raining?: number;
  ambient_temp_c?: number;
  track_temp_c?: number;
  avg_wetness?: number;
  track_grip?: number;
  cloud_coverage?: number;
};

export type CompetitorState = {
  vehicle_id: number;
  driver_name?: string;
  vehicle_name?: string;
  vehicle_model?: string;
  vehicle_class?: string;
  position?: number;
  class_position?: number;
  current_lap?: number;
  total_laps?: number;
  lap_distance?: number;
  best_lap_time?: number;
  last_lap_time?: number;
  estimated_lap_time?: number;
  finish_status?: string;
  pitstops?: number;
  pit_state?: string;
  penalties?: number;
  fuel_fraction?: number;
  last_pit_lap?: number;
  current_stint_lap?: number;
  in_pits?: boolean;
  time_behind_next?: number;
  time_behind_leader?: number;
  gap_to_player?: number;
  estimated_strategy_group?: string;
  threat_level?: string;
  is_player?: boolean;
};

export type TelemetrySnapshot = {
  timestamp: string;
  connected: boolean;
  feed_paused?: boolean;
  pause_reason?: string | null;
  session?: SessionState;
  player?: PlayerState;
  competitors: CompetitorState[];
  environment?: EnvironmentState;
  strategy?: unknown;
  message?: string;
};
