from __future__ import annotations

from typing import Optional

from sqlalchemy import Boolean, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class SessionModel(Base):
    __tablename__ = "sessions"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    created_at: Mapped[str] = mapped_column(String, nullable=False)
    track_name: Mapped[Optional[str]] = mapped_column(String)
    track_layout: Mapped[Optional[str]] = mapped_column(String)
    session_type: Mapped[Optional[str]] = mapped_column(String)
    vehicle_name: Mapped[Optional[str]] = mapped_column(String)
    vehicle_model: Mapped[Optional[str]] = mapped_column(String)
    vehicle_class: Mapped[Optional[str]] = mapped_column(String)
    started_at_game_time: Mapped[Optional[float]] = mapped_column(Float)
    ended_at_game_time: Mapped[Optional[float]] = mapped_column(Float)
    final_position: Mapped[Optional[int]] = mapped_column(Integer)
    final_class_position: Mapped[Optional[int]] = mapped_column(Integer)
    classified_status: Mapped[Optional[str]] = mapped_column(String)
    total_cars: Mapped[Optional[int]] = mapped_column(Integer)
    is_saved: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    removed_at: Mapped[Optional[str]] = mapped_column(String)


class SessionAggregateModel(Base):
    __tablename__ = "session_aggregates"
    session_id: Mapped[str] = mapped_column(String, primary_key=True)
    completed_at: Mapped[str] = mapped_column(String, nullable=False)
    duration_seconds: Mapped[Optional[float]] = mapped_column(Float)
    lap_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_distance_km: Mapped[Optional[float]] = mapped_column(Float)
    best_lap: Mapped[Optional[float]] = mapped_column(Float)
    average_lap: Mapped[Optional[float]] = mapped_column(Float)
    total_fuel_used: Mapped[Optional[float]] = mapped_column(Float)
    average_tyre_wear: Mapped[Optional[float]] = mapped_column(Float)
    average_tyre_temp: Mapped[Optional[float]] = mapped_column(Float)
    average_tyre_pressure: Mapped[Optional[float]] = mapped_column(Float)
    average_brake_temp: Mapped[Optional[float]] = mapped_column(Float)
    top_speed: Mapped[Optional[float]] = mapped_column(Float)
    latest_lap_number: Mapped[Optional[int]] = mapped_column(Integer)
    sample_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    latest_sample_json: Mapped[Optional[str]] = mapped_column(Text)
    sample_trace_json: Mapped[Optional[str]] = mapped_column(Text)
    laps_json: Mapped[Optional[str]] = mapped_column(Text)
    pit_events_json: Mapped[Optional[str]] = mapped_column(Text)
    recommendations_json: Mapped[Optional[str]] = mapped_column(Text)


class UserLifetimeStatsModel(Base):
    __tablename__ = "user_lifetime_stats"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, default=1)
    total_distance_km: Mapped[float] = mapped_column(Float, nullable=False, default=0)
    total_laps: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_driving_time: Mapped[float] = mapped_column(Float, nullable=False, default=0)
    total_sessions: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    updated_at: Mapped[Optional[str]] = mapped_column(String)


class LapValidationModel(Base):
    __tablename__ = "lap_validation_audits"
    source_lap_key: Mapped[str] = mapped_column(String, primary_key=True)
    source_type: Mapped[str] = mapped_column(String, nullable=False)
    source_session_id: Mapped[str] = mapped_column(String, nullable=False)
    source_lap_number: Mapped[str] = mapped_column(String, nullable=False)
    context_key: Mapped[Optional[str]] = mapped_column(String)
    status: Mapped[str] = mapped_column(String, nullable=False)
    reason_code: Mapped[str] = mapped_column(String, nullable=False)
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    audit_json: Mapped[Optional[str]] = mapped_column(Text)
    validated_at: Mapped[str] = mapped_column(String, nullable=False)


class PersonalBestLapModel(Base):
    __tablename__ = "personal_best_laps"
    record_key: Mapped[str] = mapped_column(String, primary_key=True)
    session_type: Mapped[str] = mapped_column(String, nullable=False)
    track: Mapped[str] = mapped_column(String, nullable=False)
    layout: Mapped[str] = mapped_column(String, nullable=False)
    car: Mapped[str] = mapped_column(String, nullable=False)
    car_class: Mapped[Optional[str]] = mapped_column(String)
    lap_time: Mapped[float] = mapped_column(Float, nullable=False)
    source_lap_key: Mapped[str] = mapped_column(String, nullable=False)
    source_type: Mapped[str] = mapped_column(String, nullable=False)
    source_session_id: Mapped[str] = mapped_column(String, nullable=False)
    source_lap_number: Mapped[str] = mapped_column(String, nullable=False)
    set_at: Mapped[Optional[str]] = mapped_column(String)
    validation_status: Mapped[str] = mapped_column(String, nullable=False, default="valid")
    record_json: Mapped[str] = mapped_column(Text, nullable=False)
    history_json: Mapped[Optional[str]] = mapped_column(Text)
    revalidated_at: Mapped[str] = mapped_column(String, nullable=False)


class AppSettingModel(Base):
    __tablename__ = "app_settings"
    key: Mapped[str] = mapped_column(String, primary_key=True)
    value: Mapped[Optional[str]] = mapped_column(Text)
    updated_at: Mapped[Optional[str]] = mapped_column(String)


class LmuDuckdbSessionModel(Base):
    __tablename__ = "lmu_duckdb_sessions"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    file_key: Mapped[str] = mapped_column(String, nullable=False)
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    file_name: Mapped[str] = mapped_column(String, nullable=False)
    file_size_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    modified_at: Mapped[Optional[str]] = mapped_column(String)
    signature: Mapped[str] = mapped_column(String, nullable=False)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[str] = mapped_column(String, nullable=False)
    synced_at: Mapped[Optional[str]] = mapped_column(String)
    track_name: Mapped[Optional[str]] = mapped_column(String)
    track_layout: Mapped[Optional[str]] = mapped_column(String)
    session_type: Mapped[Optional[str]] = mapped_column(String)
    vehicle_name: Mapped[Optional[str]] = mapped_column(String)
    vehicle_model: Mapped[Optional[str]] = mapped_column(String)
    vehicle_class: Mapped[Optional[str]] = mapped_column(String)
    started_at_game_time: Mapped[Optional[float]] = mapped_column(Float)
    ended_at_game_time: Mapped[Optional[float]] = mapped_column(Float)
    final_position: Mapped[Optional[int]] = mapped_column(Integer)
    final_class_position: Mapped[Optional[int]] = mapped_column(Integer)
    classified_status: Mapped[Optional[str]] = mapped_column(String)
    sample_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    latest_lap_number: Mapped[Optional[int]] = mapped_column(Integer)
    latest_game_time: Mapped[Optional[float]] = mapped_column(Float)
    metadata_json: Mapped[Optional[str]] = mapped_column(Text)
    warnings_json: Mapped[Optional[str]] = mapped_column(Text)
    summary_json: Mapped[Optional[str]] = mapped_column(Text)
    pit_events_json: Mapped[Optional[str]] = mapped_column(Text)


class LmuDuckdbLapModel(Base):
    __tablename__ = "lmu_duckdb_laps"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    lap_number: Mapped[str] = mapped_column(String, nullable=False)
    date: Mapped[Optional[str]] = mapped_column(String)
    track: Mapped[Optional[str]] = mapped_column(String)
    layout: Mapped[Optional[str]] = mapped_column(String)
    car: Mapped[Optional[str]] = mapped_column(String)
    car_class: Mapped[Optional[str]] = mapped_column(String)
    session_type: Mapped[Optional[str]] = mapped_column(String)
    source_file: Mapped[Optional[str]] = mapped_column(String)
    lap_time: Mapped[Optional[float]] = mapped_column(Float)
    valid_lap: Mapped[Optional[bool]] = mapped_column(Boolean)
    in_pit: Mapped[Optional[bool]] = mapped_column(Boolean)
    distance_km: Mapped[Optional[float]] = mapped_column(Float)
    fuel_start: Mapped[Optional[float]] = mapped_column(Float)
    fuel_end: Mapped[Optional[float]] = mapped_column(Float)
    fuel_used: Mapped[Optional[float]] = mapped_column(Float)
    fuel_added: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_fl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_fr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_rl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_rr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_pressure_fl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_pressure_fr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_pressure_rl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_pressure_rr: Mapped[Optional[float]] = mapped_column(Float)
    brake_temp_fl: Mapped[Optional[float]] = mapped_column(Float)
    brake_temp_fr: Mapped[Optional[float]] = mapped_column(Float)
    brake_temp_rl: Mapped[Optional[float]] = mapped_column(Float)
    brake_temp_rr: Mapped[Optional[float]] = mapped_column(Float)
    track_temp: Mapped[Optional[float]] = mapped_column(Float)
    ambient_temp: Mapped[Optional[float]] = mapped_column(Float)
    engine_oil_temp: Mapped[Optional[float]] = mapped_column(Float)
    engine_water_temp: Mapped[Optional[float]] = mapped_column(Float)
    max_speed: Mapped[Optional[float]] = mapped_column(Float)
    average_speed: Mapped[Optional[float]] = mapped_column(Float)
    finish_position: Mapped[Optional[int]] = mapped_column(Integer)
    finish_status: Mapped[Optional[str]] = mapped_column(String)


class TelemetrySampleModel(Base):
    __tablename__ = "telemetry_samples"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    timestamp: Mapped[str] = mapped_column(String, nullable=False)
    game_time: Mapped[Optional[float]] = mapped_column(Float)
    lap_number: Mapped[Optional[int]] = mapped_column(Integer)
    position: Mapped[Optional[int]] = mapped_column(Integer)
    class_position: Mapped[Optional[int]] = mapped_column(Integer)
    current_lap_time: Mapped[Optional[float]] = mapped_column(Float)
    last_lap_time: Mapped[Optional[float]] = mapped_column(Float)
    best_lap_time: Mapped[Optional[float]] = mapped_column(Float)
    speed_kph: Mapped[Optional[float]] = mapped_column(Float)
    gear: Mapped[Optional[int]] = mapped_column(Integer)
    rpm: Mapped[Optional[float]] = mapped_column(Float)
    fuel_liters: Mapped[Optional[float]] = mapped_column(Float)
    fuel_capacity_liters: Mapped[Optional[float]] = mapped_column(Float)
    engine_oil_temp: Mapped[Optional[float]] = mapped_column(Float)
    engine_water_temp: Mapped[Optional[float]] = mapped_column(Float)
    throttle: Mapped[Optional[float]] = mapped_column(Float)
    brake: Mapped[Optional[float]] = mapped_column(Float)
    steering: Mapped[Optional[float]] = mapped_column(Float)
    abs_active: Mapped[Optional[bool]] = mapped_column(Boolean)
    tc_active: Mapped[Optional[bool]] = mapped_column(Boolean)
    abs_setting: Mapped[Optional[int]] = mapped_column(Integer)
    abs_max: Mapped[Optional[int]] = mapped_column(Integer)
    tc_setting: Mapped[Optional[int]] = mapped_column(Integer)
    tc_max: Mapped[Optional[int]] = mapped_column(Integer)
    tc_slip_setting: Mapped[Optional[int]] = mapped_column(Integer)
    tc_cut_setting: Mapped[Optional[int]] = mapped_column(Integer)
    brake_temp_fl: Mapped[Optional[float]] = mapped_column(Float)
    brake_temp_fr: Mapped[Optional[float]] = mapped_column(Float)
    brake_temp_rl: Mapped[Optional[float]] = mapped_column(Float)
    brake_temp_rr: Mapped[Optional[float]] = mapped_column(Float)
    brake_pressure_fl: Mapped[Optional[float]] = mapped_column(Float)
    brake_pressure_fr: Mapped[Optional[float]] = mapped_column(Float)
    brake_pressure_rl: Mapped[Optional[float]] = mapped_column(Float)
    brake_pressure_rr: Mapped[Optional[float]] = mapped_column(Float)
    ride_height_fl: Mapped[Optional[float]] = mapped_column(Float)
    ride_height_fr: Mapped[Optional[float]] = mapped_column(Float)
    ride_height_rl: Mapped[Optional[float]] = mapped_column(Float)
    ride_height_rr: Mapped[Optional[float]] = mapped_column(Float)
    front_ride_height: Mapped[Optional[float]] = mapped_column(Float)
    rear_ride_height: Mapped[Optional[float]] = mapped_column(Float)
    suspension_deflection_fl: Mapped[Optional[float]] = mapped_column(Float)
    suspension_deflection_fr: Mapped[Optional[float]] = mapped_column(Float)
    suspension_deflection_rl: Mapped[Optional[float]] = mapped_column(Float)
    suspension_deflection_rr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_fl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_fr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_rl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_rr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_load_fl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_load_fr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_load_rl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_load_rr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_pressure_fl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_pressure_fr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_pressure_rl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_pressure_rr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_temp_fl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_temp_fr: Mapped[Optional[float]] = mapped_column(Float)
    tyre_temp_rl: Mapped[Optional[float]] = mapped_column(Float)
    tyre_temp_rr: Mapped[Optional[float]] = mapped_column(Float)
    track_temp: Mapped[Optional[float]] = mapped_column(Float)
    ambient_temp: Mapped[Optional[float]] = mapped_column(Float)
    rain: Mapped[Optional[float]] = mapped_column(Float)
    wetness: Mapped[Optional[float]] = mapped_column(Float)
    pitstops: Mapped[Optional[int]] = mapped_column(Integer)
    in_pits: Mapped[Optional[bool]] = mapped_column(Boolean)
    pit_state: Mapped[Optional[str]] = mapped_column(String)


class LapSummaryModel(Base):
    __tablename__ = "lap_summaries"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    lap_number: Mapped[int] = mapped_column(Integer, nullable=False)
    lap_time: Mapped[Optional[float]] = mapped_column(Float)
    sector1: Mapped[Optional[float]] = mapped_column(Float)
    sector2: Mapped[Optional[float]] = mapped_column(Float)
    sector3: Mapped[Optional[float]] = mapped_column(Float)
    fuel_start: Mapped[Optional[float]] = mapped_column(Float)
    fuel_end: Mapped[Optional[float]] = mapped_column(Float)
    fuel_used: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_start: Mapped[Optional[float]] = mapped_column(Float)
    tyre_wear_end: Mapped[Optional[float]] = mapped_column(Float)
    valid_lap: Mapped[Optional[bool]] = mapped_column(Boolean)
    in_pit: Mapped[Optional[bool]] = mapped_column(Boolean)
    under_yellow: Mapped[Optional[bool]] = mapped_column(Boolean)


class PitEventModel(Base):
    __tablename__ = "pit_events"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    vehicle_id: Mapped[Optional[int]] = mapped_column(Integer)
    driver_name: Mapped[Optional[str]] = mapped_column(String)
    lap_number: Mapped[Optional[int]] = mapped_column(Integer)
    pit_entry_time: Mapped[Optional[float]] = mapped_column(Float)
    pit_exit_time: Mapped[Optional[float]] = mapped_column(Float)
    stationary_time: Mapped[Optional[float]] = mapped_column(Float)
    total_pit_loss: Mapped[Optional[float]] = mapped_column(Float)
    detected_from: Mapped[Optional[str]] = mapped_column(String)


class RecommendationModel(Base):
    __tablename__ = "recommendations"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    timestamp: Mapped[str] = mapped_column(String, nullable=False)
    lap_number: Mapped[Optional[int]] = mapped_column(Integer)
    recommendation_type: Mapped[Optional[str]] = mapped_column(String)
    priority: Mapped[Optional[str]] = mapped_column(String)
    message: Mapped[Optional[str]] = mapped_column(Text)
    reason_codes: Mapped[Optional[str]] = mapped_column(Text)
    assumptions_json: Mapped[Optional[str]] = mapped_column(Text)
    accepted: Mapped[Optional[bool]] = mapped_column(Boolean)


class AssumptionModel(Base):
    __tablename__ = "assumptions"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    pit_loss_seconds: Mapped[Optional[float]] = mapped_column(Float)
    pit_stationary_seconds: Mapped[Optional[float]] = mapped_column(Float)
    fuel_safety_margin_liters: Mapped[Optional[float]] = mapped_column(Float)
    fuel_safety_margin_laps: Mapped[Optional[float]] = mapped_column(Float)
    max_tyre_wear: Mapped[Optional[float]] = mapped_column(Float)
    normal_lap_time: Mapped[Optional[float]] = mapped_column(Float)
    safety_car_pit_loss_seconds: Mapped[Optional[float]] = mapped_column(Float)
    updated_at: Mapped[Optional[str]] = mapped_column(String)
